USE[MOVIEDB]

CREATE TABLE LOGINS( 
	LOGINNAME varchar(10) PRIMARY KEY,
	PASSWORD char (5) NOT NULL
);

CREATE TABLE MOVIES(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	RELEASEDATE DATETIME NOT NULL,
	GENRE TINYINT NOT NULL,
	SUMMARY VARCHAR(250) NOT NULL,
	INDEX [I_MOVIES] NONCLUSTERED
	(
		TITLE
	)
);

CREATE TABLE MOVIEDIRECTORS(
	MOVIEID INT NOT NULL,
	DIRECTOR VARCHAR(50) NOT NULL,
	CONSTRAINT [U_MOVIEDIRECTORS] UNIQUE NONCLUSTERED
    (
        MOVIEID, DIRECTOR
    ),
	INDEX [I_MOVIEDIRECTORS] NONCLUSTERED
	(
		DIRECTOR
	)
);

CREATE TABLE MOVIEACTORS(
	MOVIEID INT NOT NULL,
	ACTOR VARCHAR(50) NOT NULL,
	CONSTRAINT [U_MOVIEACTORS] UNIQUE NONCLUSTERED
    (
        MOVIEID, ACTOR
    ),
	INDEX [I_MOVIEACTORS] NONCLUSTERED
	(
		ACTOR
	)
);

CREATE TABLE SYSTEMPARAMS(
	PARAMNAME VARCHAR(50) PRIMARY KEY,
	PARAMTYPE TINYINT NOT NULL, -- 0: TEXT, 1: INT, 2: FLOAT, 3: DATETIME,
	PARAMTEXT VARCHAR(250),
	PARAMINTEGER INT,
	PARAMFLOAT FLOAT,
	PARAMDATE DATETIME
);
